zephyrproject-rtos/hal_silabs

- gecko/CMakeLists.txt
Enable compilation of Silabs Gecko ADC sources
Signed-off-by: Oane Kingma <o.kingma@interay.com>
> modules: hal_silabs: Add Silabs Gecko ADC sources

- gecko/emlib/inc/em_gpio.h
The macro GPIO_PORT_VALID() is used in boolean operations in
em_gpio.c. In some compiler/ccache configurations this produced the
warning "using integer constants in boolean context
[-Werror=int-in-bool-context]"
See https://github.com/zephyrproject-rtos/zephyr/issues/16968 for more
details.
This patch needs to be reapplied every time SiLabs library version is
updated.
Signed-off-by: Christian Taedcke <christian.taedcke@lemonbeat.com>
> hal_silabs: patch: Return bool from macro GPIO_PORT_VALID

- gecko/CMakeLists.txt
Build em_burtc.c driver when SOC_GECKO_BURTC is set in Kconfig
> modules: hal_silabs: support compiling em_burtc driver

- gecko/CMakeLists.txt
- gecko/emlib/inc/em_iadc.h
- gecko/emlib/src/em_iadc.c
This PR adds HAL components required for adding Gecko IADC driver in Zephyr.
Origin: Silicon Labs Gecko SDK
URL: https://github.com/SiliconLabs/gecko_sdk
Version: 4.2.0
Purpose: Gecko IADC source files are updated.
License: Zlib
Maintained-by: External
> modules: hal_silabs: Update Silabs Gecko IADC sources

- gecko/CMakeLists.txt
- gecko/platform/radio/rail_lib/plugin/pa-conversions/efr32xg24/config/sl_rail_util_pa_config.h
- gecko/platform/radio/rail_lib/plugin/pa-conversions/efr32xg24/sl_rail_util_pa_curves_10dbm.h
- gecko/platform/radio/rail_lib/plugin/pa-conversions/efr32xg24/sl_rail_util_pa_curves_20dbm.h
- zephyr/module.yml
This PR adds BLE support for EFR32XG24. It includes RAIL library with binary blobs for EFR32XG24 platform. Binary blobs are downloaded with the west blobs command.
> modules: hal_silabs: add BLE support for EFR32XG24

- gecko/CMakeLists.txt
Currently on zephyr, RAIL library is used only by Bluetooth applications and depends on BT_SILABS_HCI option. RAIL library is needed to use efr32 radio regardless of the protocol used. As other wireless protocols will certainly be supported in zephyr for efr32, I think it's good idea to use an other option to use RAIL.
> zephyr: Kconfig: use SOC_GECKO_USE_RAIL Kconfig option to use RAIL

- gecko/CMakeLists.txt
This will be needed for `efr32bg22_brd4184b` board support in Zephyr.
> zephyr: define PRODUCT_NO for efr32bg22_brd4184b

- gecko/CMakeLists.txt
Right now, CMake errors out if either `CONFIG_SOC_GECKO_SERIES1` or `CONFIG_SOC_GECKO_SERIES2` is undefined. This check is for adding the right RAIL headers for the chosen SoC series.
Using RAIL is not required for normal SoC operation in Zephyr, so erroring out here is not required.
> gecko/CMakeLists: don't error out on missing SOC_GECKO_SERIES1/2

- gecko/CMakeLists.txt
Moved all RF related code (include directories, BT, RAIL) under CONFIG_SOC_FAMILY_EFR32, as this code is irrelevant for the EFM32 family.
> gecko/CMakeLists.txt: Put RF related code under EFR32 config

- gecko/CMakeLists.txt
- gecko/service/device_init/config/s2/sdid230/sl_device_init_dpll_config.h
Please see the original slcc sdid value: https://github.com/SiliconLabs/gecko_sdk/blob/gsdk_4.3/platform/Device/component/efr32bg27c140f768im40.slcc#L70
> gecko: Fix sdid for xg27 part

- gecko/Device/SiliconLabs/EFR32BG22/Include/efr32bg22_syscfg.h
- gecko/Device/SiliconLabs/EFR32BG22/Include/system_efr32bg22.h
- gecko/Device/SiliconLabs/EFR32BG22/Source/system_efr32bg22.c
- gecko/Device/SiliconLabs/EFR32BG27/Include/efr32bg27_dcdc.h
- gecko/Device/SiliconLabs/EFR32BG27/Include/efr32bg27_devinfo.h
- gecko/Device/SiliconLabs/EFR32BG27/Include/efr32bg27_eusart.h
- gecko/Device/SiliconLabs/EFR32BG27/Include/efr32bg27_gpio.h
- gecko/Device/SiliconLabs/EFR32BG27/Include/efr32bg27_ldma.h
- gecko/Device/SiliconLabs/EFR32BG27/Include/efr32bg27c140f768im32.h
- gecko/Device/SiliconLabs/EFR32BG27/Include/efr32bg27c140f768im40.h
- gecko/Device/SiliconLabs/EFR32BG27/Include/efr32bg27c230f768im32.h
- gecko/Device/SiliconLabs/EFR32BG27/Include/efr32bg27c230f768im40.h
- gecko/Device/SiliconLabs/EFR32BG27/Include/efr32bg27c320f768gj39.h
- gecko/Device/SiliconLabs/EFR32BG27/Include/system_efr32bg27.h
- gecko/Device/SiliconLabs/EFR32BG27/Source/system_efr32bg27.c
- gecko/Device/SiliconLabs/EFR32MG24/Include/efr32mg24_mpahbram.h
- gecko/Device/SiliconLabs/EFR32MG24/Include/efr32mg24_syscfg.h
- gecko/Device/SiliconLabs/EFR32MG24/Include/system_efr32mg24.h
- gecko/Device/SiliconLabs/EFR32MG24/Source/system_efr32mg24.c
Origin: Silicon Labs Gecko SDK
URL: https://github.com/SiliconLabs/gecko_sdk
Version: 4.4.0
Purpose: Update hal_silabs to gecko_sdk v4.4.0.
Update the EFR32BG22, BG27 and MG24 device files inside gecko/Device/SiliconLabs/ from gecko_sdk to align the codebase of hal_silabs with gecko_sdk 4.4.0.
> gecko: Update BG22, BG27 and MG24 Device files | Update to GSDK 4.4.0

- gecko/CMakeLists.txt
The `SOC_GECKO_SERIESx` Kconfig symbol no longer exists in Zephyr and was replaced with `SOC_FAMILY_SILABS_Sx` during migration to hwmv2.
References (this will fix related issue after updating west manifest): https://github.com/zephyrproject-rtos/zephyr/issues/69902
> gecko/cmake: replace 'SOC_GECKO_SERIESx' with 'SOC_FAMILY_SILABS_Sx'

- gecko/service/sleeptimer/inc/peripheral_sysrtc.h
- gecko/service/sleeptimer/inc/peripheral_sysrtc_compat.h
- gecko/service/sleeptimer/src/peripheral_sysrtc.c
Origin: Silicon Labs Gecko SDK
URL: https://github.com/SiliconLabs/gecko_sdk
Version: 4.4.0
Purpose: Update hal_silabs to gecko_sdk v4.4.0.
Updated the peripheral_sysrtc.h, peripheral_sysrtc.c and added peripheral_sysrtc_compat.h. The files are taken from gecko_sdk 4.4.0. These files are required for counter support in silabs boards.
The mentioned files are present in gecko_sdk at 
peripheral_sysrtc.h - https://github.com/SiliconLabs/gecko_sdk/blob/gsdk_4.4/platform/peripheral/inc/peripheral_sysrtc.h
peripheral_sysrtc.c - https://github.com/SiliconLabs/gecko_sdk/blob/gsdk_4.4/platform/peripheral/src/peripheral_sysrtc.c
peripheral_sysrtc_compat.h - https://github.com/SiliconLabs/gecko_sdk/blob/gsdk_4.4/platform/peripheral/inc/peripheral_sysrtc_compat.h
> gecko: service: sysrtc files updated

- zephyr/module.yml
This is consistent with most other HALs and also makes the fetching of binary blobs consistent ("west blobs fetch hal_silabs").
> zephyr: Add an explicit name for the module

- scripts/patch_simplicity_sdk.sh
- simplicity_sdk/platform/radio/rail_lib/plugin/pa-conversions/pa_conversions_efr32.c
Zephyr defines the MAX() macro in util.h, which causes a conflict with a locally defined macro of the same name.
> simplicity_sdk: Patch pa_conversions_efr32.c to not conflict

- CODEOWNERS
Add a CODEOWNERS file based on the Maintainers and Collaborators from the Zephyr main tree MAINTAINERS.yml file.
> CODEOWNERS: Add basic skeleton

- wiseconnect/components/device/silabs/si91x/wireless/src/sl_rsi_utility.c
Corrects the assignment of SL_SI91X_TERMINATE_BUS_THREAD_EVENT to si91x_bus_event instead of si91x_event, ensuring proper ACK reception and successful platform deinitialization.
> wiseconnect: Fix si91x_bus event during platform deinitialization

- wiseconnect/components/device/silabs/si91x/wireless/ahb_interface/src/rsi_hal_mcu_m4_rom.c
- wiseconnect/components/device/silabs/si91x/wireless/socket/src/sl_si91x_socket_utility.c
Corrected the assignments of SL_SI91X_SOCKET_DATA_TX_PENDING_EVENT,
SL_SI91X_SOCKET_COMMAND_TX_PENDING_EVENT, and
SL_SI91X_TA_BUFFER_FULL_CLEAR_EVENT to si91x_bus_event instead of
si91x_event, ensuring proper setting for the bus events.
> wiseconnect: Fixed setting of si91x bus events in the driver path

- scripts/import_wiseconnect.py
- wiseconnect/components/device/silabs/si91x/mcu/drivers/service/sleeptimer/src/sl_sleeptimer_hal_si91x_sysrtc.c
Origin: Silicon Labs WiseConnect SDK
License: Zlib
URL: https://github.com/siliconlabs/wiseconnect
Commit: 68e44ea22070bb0e594b9974047aed687538aca7
Version: v3.4.0-cf
Purpose: Add Sleeptimer support for SiWx917
> wiseconnect: Sleeptimer SDK files

- wiseconnect/components/device/silabs/si91x/wireless/inc/sl_rsi_utility.h
- wiseconnect/components/device/silabs/si91x/wireless/src/sl_rsi_utility.c
Allocate stack memory and control blocks statically for `bus thread` and `event thread` instead of dynamically. This change addresses a known issue in Zephyr related to dynamic allocation of stack and control blocks.
> wiseconnect: Use static allocation for threads

- wiseconnect/components/device/silabs/si91x/mcu/drivers/unified_peripheral_drivers/src/sl_si91x_peripheral_gpio.c
gcc 14.3 complains:
error: conflicting types for
'sl_si91x_gpio_select_group_interrupt_wakeup' due to enum/integer
mismatch; have 'void(uint8_t, sl_si91x_group_interrupt_t, uint8_t)'
{aka 'void(unsigned char, sl_si91x_group_interrupt_t, unsigned
char)'} [-Werror=enum-int-mismatch]
> wiseconnect: Fix compiler warning

- wiseconnect/components/device/silabs/si91x/wireless/src/sl_si91x_driver.c
The commit `a0095a7` ensures that the 11ax configuration is applied only when operating in client mode, unfortunately it removed here `bb7c2d4`
> wiseconnect: Restore 802.11ax config only in client mode

- wiseconnect/components/device/silabs/si91x/mcu/drivers/unified_peripheral_drivers/src/sl_si91x_peripheral_gpio.c
GCC 14.3 complains when a function declaration and definition have a mismatch between an enum and an integer type.  Adjust the definition of sl_si91x_gpio_select_group_interrupt_wakeup so that the definition matches the prototype so that both use the enum type.
> si91x: Don't use uint8_t for sl_si91x_gpio_wakeup_t parameter

- wiseconnect/components/device/silabs/si91x/mcu/core/chip/src/rsi_deepsleep_soc.c
Fix the rsi_deepsleep_soc.c to use the cmsis_6 define names.
> si91x: use the cmsis_6 defines

- scripts/gen_pinctrl.py
In order to bring consistency in-tree, migrate all code to the new prefix <zephyr/...>. Refer to #45388 for more details.
> scripts: gen_pinctrl.py: migrate includes to <zephyr/...>

- simplicity_sdk/platform/service/power_manager/src/sleep_loop/sl_power_manager_hal_s2.c
The goal of this PR is to add a patch needed to fix a bug where the SLEEPDEEP bit is not cleared properly after a wakeup from EM2.
> simplicity_sdk: Patch in sl_power_manager_hal_s2.c

- scripts/import_wiseconnect.py
- wiseconnect/components/device/silabs/si91x/wireless/ble/src/sl_si91x_ble.c
wiseconnect: BLE SDK files
Origin: Silicon Labs WiseConnect SDK
License: Zlib
URL: https://github.com/siliconlabs/wiseconnect
Commit: ca4c4b06c5549cf935994fcdfb1faddd232aadf1
Version: v3.5.0
Purpose: Add BT/BLE Power Manager support for SiWx91x
Signed-off-by: Mohamed Irfan [irfan.mohamed@silabs.com]
> Ble pm siwx91x

- zephyr/module.yml
Add liblinklayer.a for xg21 to module.yml
> zephyr: Add BT controller library for xg21

- wiseconnect/components/device/silabs/si91x/mcu/hal/src/sl_si91x_hal_soc_soft_reset.c
Inclusion of cmsis_os2.h creates a dependency to CMSIS in Zephyr. However, it seems this include is just a mistake since:
- Nothing in sl_si91x_hal_soc_soft_reset.c depends on CMSIS API
- This include has been removed in Wiseconnect v3.5.2
So, let's remove it.
> wiseconnect: Drop non-required dependency on CMSIS API
